### ISSUE TITLE
After sign out , app is not redirecting to post_sign_out url

### ISSUE THREAD

**Issue by datasleek** [Azure-Samples/ms-identity-python-django-tutorial#1]
I ran the application ```1-Authentication sign-in```. I was able to sign in and see token details. When i clicked on Sign out button on the top right, it took me to microsoft signout window and logged me out. But when i again hit http://localhost:8000, i was still signed in. I inspected a bit. After sign_out, app should redirect to post_sign_out url to clear the identity_context_data. But app is not redirecting to post_sign_out url. Here is the trace

```
[05/Apr/2021 18:15:10] "GET / HTTP/1.1" 200 2503
----------------------------------------
Exception happened during processing of request from ('127.0.0.1', 60059)
Traceback (most recent call last):
  File "c:\users\hp\appdata\local\programs\python\python37-32\lib\socketserver.py", line 650, in process_request_thread
    self.finish_request(request, client_address)
  File "c:\users\hp\appdata\local\programs\python\python37-32\lib\socketserver.py", line 360, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "c:\users\hp\appdata\local\programs\python\python37-32\lib\socketserver.py", line 720, in __init__
    self.handle()
  File "C:\Users\hp\Desktop\ms-identity-python-django-tutorial\1-Authentication\sign-in\venv\lib\site-packages\django\core\servers\basehttp.py", line 174, in handle
    self.handle_one_request()
  File "C:\Users\hp\Desktop\ms-identity-python-django-tutorial\1-Authentication\sign-in\venv\lib\site-packages\django\core\servers\basehttp.py", line 182, in handle_
one_request
    self.raw_requestline = self.rfile.readline(65537)
  File "c:\users\hp\appdata\local\programs\python\python37-32\lib\socket.py", line 589, in readinto
    return self._sock.recv_into(b)
ConnectionAbortedError: [WinError 10053] An established connection was aborted by the software in your host machine
----------------------------------------
auth/sign_out: signing out username: Abhinav Soni
[05/Apr/2021 18:15:13] "GET /auth/sign_out HTTP/1.1" 302 0
```

If everything would have gone smoothly then i would have seen one more print statement i.e ``` auth/post_sign_out: clearing session for username: Abhinav Soni```

Here are the snippets of sign_out and post_sign_out views:

    def sign_out(self, request):
        self.logger.debug(f"{self.prefix}{self.endpoints.sign_out}: signing out username: {request.identity_context_data.username}")
        print(f"{self.prefix}{self.endpoints.sign_out}: signing out username: {request.identity_context_data.username}")
        return self.ms_identity_web.sign_out(request.build_absolute_uri(reverse(self.endpoints.post_sign_out)))    # send the user to Azure AD logout endpoint

    def post_sign_out(self, request):
        self.logger.debug(f"{self.prefix}{self.endpoints.post_sign_out}: clearing session for username: {request.identity_context_data.username}")
        print(f"{self.prefix}{self.endpoints.post_sign_out}: clearing session for username: {request.identity_context_data.username}")
        self.ms_identity_web.remove_user(request.identity_context_data.username)  # remove user auth from session on successful logout
        return redirect(reverse('index'))

**Comment by e-scheer** [comment]
You morelikely forgot to add the logout_url in the azure portal: https://stackoverflow.com/questions/45935305/azure-ad-logout-url-not-redirecting

**Comment by ckittel** [comment]
@datasleek, can you let us know if @e-scheer's answer helped you out here?  I'm going to close this issue, but if you need it reopened, please do so.  Thanks.
